# All makefile fragments assume that $(srcdir) points to the gcc
# directory, not the language subdir
srcdir = /home/voyager717/Downloads/SDK_Sourcecode/build_openwrt_new/AX3000-MT7981-Z8102AX/build_dir/toolchain-aarch64_cortex-a53_gcc-8.4.0_musl/gcc-8.4.0/gcc
-include ./gcc-interface/Makefile
-include ../gcc-interface/Makefile
