#!/bin/sh -e

libdir="/home/voyager717/Downloads/SDK_Sourcecode/build_openwrt_new/AX3000-MT7981-Z8102AX/build_dir/target-aarch64_cortex-a53_musl/nghttp2-1.43.0/lib"
if [ -d "$libdir/.libs" ]; then
    libdir="$libdir/.libs"
fi

export CGO_CFLAGS="-I/home/voyager717/Downloads/SDK_Sourcecode/build_openwrt_new/AX3000-MT7981-Z8102AX/build_dir/target-aarch64_cortex-a53_musl/nghttp2-1.43.0/lib/includes -I/home/voyager717/Downloads/SDK_Sourcecode/build_openwrt_new/AX3000-MT7981-Z8102AX/build_dir/target-aarch64_cortex-a53_musl/nghttp2-1.43.0/lib/includes "
export CGO_CPPFLAGS=""
export CGO_LDFLAGS="-L$libdir "
export LD_LIBRARY_PATH="$libdir"
export GODEBUG=cgocheck=0
"$@"
