# generated by ./configure on Fri Feb 28 01:26:30 UTC 2025
SRCDIR = .
CPPFLAGS += -I.
# detected libiptc version 1.8.7
IPTABLES_PCFILE_FOUND = 1
CFLAGS += -I/home/voyager717/Downloads/SDK_Sourcecode/build_openwrt_new/AX3000-MT7981-Z8102AX/staging_dir/target-aarch64_cortex-a53_musl/usr/include 
LDLIBS += -lip4tc -lip6tc 
LDFLAGS += -L/home/voyager717/Downloads/SDK_Sourcecode/build_openwrt_new/AX3000-MT7981-Z8102AX/staging_dir/target-aarch64_cortex-a53_musl/usr/lib 
CFLAGS += -I/home/voyager717/Downloads/SDK_Sourcecode/build_openwrt_new/AX3000-MT7981-Z8102AX/staging_dir/target-aarch64_cortex-a53_musl/usr/include 
LDLIBS += -lcap-ng 
LDFLAGS += -L/home/voyager717/Downloads/SDK_Sourcecode/build_openwrt_new/AX3000-MT7981-Z8102AX/staging_dir/target-aarch64_cortex-a53_musl/usr/lib 
