#ifndef LIBGCC_TM_H
#define LIBGCC_TM_H
/* Automatically generated by mkheader.sh.  */
#include "/home/voyager717/Downloads/SDK_Sourcecode/build_openwrt_new/AX3000-MT7981-Z8102AX/build_dir/toolchain-aarch64_cortex-a53_gcc-8.4.0_musl/gcc-8.4.0/libgcc/config/aarch64/value-unwind.h"
#endif /* LIBGCC_TM_H */
