/*
 * WARNING: do not edit!
 * Generated by util/mkbuildinf.pl
 *
 * Copyright 2014-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define PLATFORM "platform: linux-aarch64-openwrt"
#define DATE "built on: Fri Jun 16 10:11:54 2023 UTC"

/*
 * Generate compiler_flags as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','a','a','r','c','h','6',
    '4','-','o','p','e','n','w','r','t','-','l','i','n','u','x','-',
    'm','u','s','l','-','g','c','c',' ','-','f','P','I','C',' ','-',
    'p','t','h','r','e','a','d',' ','-','W','a',',','-','-','n','o',
    'e','x','e','c','s','t','a','c','k',' ','-','W','a','l','l',' ',
    '-','O','3',' ','-','O','s',' ','-','p','i','p','e',' ','-','m',
    'c','p','u','=','c','o','r','t','e','x','-','a','5','3',' ','-',
    'f','n','o','-','c','a','l','l','e','r','-','s','a','v','e','s',
    ' ','-','f','n','o','-','p','l','t',' ','-','f','h','o','n','o',
    'u','r','-','c','o','p','t','s',' ','-','W','n','o','-','e','r',
    'r','o','r','=','u','n','u','s','e','d','-','b','u','t','-','s',
    'e','t','-','v','a','r','i','a','b','l','e',' ','-','W','n','o',
    '-','e','r','r','o','r','=','u','n','u','s','e','d','-','r','e',
    's','u','l','t',' ','-','W','f','o','r','m','a','t',' ','-','W',
    'e','r','r','o','r','=','f','o','r','m','a','t','-','s','e','c',
    'u','r','i','t','y',' ','-','f','s','t','a','c','k','-','p','r',
    'o','t','e','c','t','o','r',' ','-','D','_','F','O','R','T','I',
    'F','Y','_','S','O','U','R','C','E','=','1',' ','-','W','l',',',
    '-','z',',','n','o','w',' ','-','W','l',',','-','z',',','r','e',
    'l','r','o',' ','-','D','P','I','C',' ','-','f','P','I','C',' ',
    '-','f','f','u','n','c','t','i','o','n','-','s','e','c','t','i',
    'o','n','s',' ','-','f','d','a','t','a','-','s','e','c','t','i',
    'o','n','s',' ','-','z','n','o','w',' ','-','z','r','e','l','r',
    'o',' ','-','D','O','P','E','N','S','S','L','_','U','S','E','_',
    'N','O','D','E','L','E','T','E',' ','-','D','O','P','E','N','S',
    'S','L','_','P','I','C',' ','-','D','O','P','E','N','S','S','L',
    '_','C','P','U','I','D','_','O','B','J',' ','-','D','O','P','E',
    'N','S','S','L','_','B','N','_','A','S','M','_','M','O','N','T',
    ' ','-','D','S','H','A','1','_','A','S','M',' ','-','D','S','H',
    'A','2','5','6','_','A','S','M',' ','-','D','S','H','A','5','1',
    '2','_','A','S','M',' ','-','D','K','E','C','C','A','K','1','6',
    '0','0','_','A','S','M',' ','-','D','V','P','A','E','S','_','A',
    'S','M',' ','-','D','E','C','P','_','N','I','S','T','Z','2','5',
    '6','_','A','S','M',' ','-','D','P','O','L','Y','1','3','0','5',
    '_','A','S','M',' ','-','D','N','D','E','B','U','G',' ','-','D',
    'O','P','E','N','S','S','L','_','S','M','A','L','L','_','F','O',
    'O','T','P','R','I','N','T','\0'
};
